name: clone workflow
on:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/20 1 * * *"

jobs:

  cron-workflow-job:
    runs-on: ubuntu-latest
    steps:
     - run: echo "clone workflow"