name: first workflow

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "this is version name workflow_dispatch"
        required: true












jobs:

  First-workflow-job:

    name: first job

    runs-on: ubuntu-latest

    steps:

      - name: before checkout

        run: ls

        shell: bash


      - name: uses checkout
        uses: actions/checkout@v6

      - name: after checkout

        run: ls

        shell: bash     

        



      
