name: first workflow

on:
  workflow-dispatch:
     inputs:
      versionName:
        required: true
        description: "this is version Name"











#  push:

#    branches:

#      - "main"

jobs:

  First-workflow-job:

    name: first job

    runs-on: ubuntu-latest

    steps:

      - name: before checkout

        run: ls

        shell: bash


      - name: uses checkout
        uses: actions/checkout@v6

      - name: after checkout

        run: ls

        shell: bash     

        



      
